### PR TITLE
Feature/unit tests action service

### PR DESCRIPTION
**Pull request by marcandregirard**
Completely covers the Action service with unit tests. The naming of tests might need to improve and I'm looking for suggestions for it. 

Other than that, small improvement to the code with the data class for MapPoint and some tweaks here and there as I get to understand more about Kotlin.

### CODE REVIEW

**Comment by mrheaumeproulx** [comment]
I have a tendency to write tests to be more descriptive:

- Verify that Mountains return Mine action -> Mountain map points should return Mine action
Simply added "maps points" to define what mountains relates to. Added "should" as well, I do not know if it is necessary

- Executing CREATE_BASE action returns false if there is no hero -> Executing CREATE_BASE action returns false when the user has no hero
Added the reference to user to better understands what no hero means. 

I think bein a bit more descriptive makes it easier to understand the test at first glance.
That's my suggestion, what do you think?

There are some typos as well in the names, such as line 182 in ActionServiceTests, where "there" is extra

**Comment by marcandregirard** [comment]
I definitely agree, normally I used the Should do something When method is called With parameters.

I was a bit quick and dirty on the tests names to see what you were used to. I feel like being a bit free form was more interesting than  following blindy the ShouldWhenWith

**Comment by mrheaumeproulx** [comment]
I think you did is good enough, we can keep it simple while being descriptive enough

**Comment by marcandregirard** [comment]
I'll quickly update the names and then we'll merge. I feel like the free form is great too.

How did you find Kotlin and the test did you follow easily what was going on?

**Comment by marcandregirard** [comment]
So names are fix you can complete the pull when you approve it @mrheaumeproulx

**Pull request merged**
